version: '3.8'

volumes:
  data:
    driver: local
  zero_replica:
    driver: local

configs:
  seed:
    file: ./seed.sql
  schema:
    file: ../../zero-schema.json



# networks:
#   vps:
#     external: true

services:
  postgres:
    image: postgres:16.2-alpine
    user: postgres
    restart: always
    healthcheck:
      test: 'pg_isready -U user --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    command: |
      postgres 
      -c wal_level=logical
      -c max_wal_senders=10 
      -c max_replication_slots=5 
      -c hot_standby=on 
      -c hot_standby_feedback=on
    volumes:
      - data:/var/lib/postgresql/data
    configs:
      - source: seed
        target: /docker-entrypoint-initdb.d/seed.sql
    # networks:
    #   - vps

  zero:
    image: rocicorp/zero:0.12.2025013100
    env_file:
      - ./.env
    environment:
      ZERO_UPSTREAM_DB: "postgresql://user:password@postgres:5432/postgres"
      ZERO_CVR_DB:     "postgresql://user:password@postgres:5432/postgres"
      ZERO_CHANGE_DB:  "postgresql://user:password@postgres:5432/postgres"
      ZERO_REPLICA_FILE: /tmp/zstart_replica.db
      ZERO_SCHEMA_FILE: /opt/app/zero-schema.json
    ports:
      - published: 4848
        target: 4848
    configs:
      - source: schema
        target: /opt/app/zero-schema.json
    volumes:
      - zero_replica:/tmp
    # networks:
    #   - vps


