
networks:
  vps:
    external: true

volumes:
  zstart_pgdata:
    driver: local
  zero_replica:
    driver: local

services:
  frontend:
    image: ghcr.io/baranuel/casefiles:${GIT_COMMIT_HASH:-latest}
    env_file:
      - ./.env
    networks:
      - vps

  postgres:
    image: postgres:16.2-alpine
    user: postgres
    healthcheck:
      test: 'pg_isready -U user --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env
    ports:
      - published: 5432
        target: 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=5
      -c hot_standby=on
      -c hot_standby_feedback=on
    volumes:
      - type: volume
        source: zstart_pgdata
        target: /var/lib/postgresql/data
      - type: bind
        source: ../seed.sql
        target: /docker-entrypoint-initdb.d/seed.sql 
    networks:
      - vps


  zero:
    image: rocicorp/zero:0.12.2025013100
    env_file:
      - ./.env
    environment:
      ZERO_UPSTREAM_DB: "postgresql://casefiles:a8f5f167f44f4964e6c998dee827110c@dev_postgres:5432/zstart"
      ZERO_CVR_DB:     "postgresql://casefiles:a8f5f167f44f4964e6c998dee827110c@dev_postgres:5432/zstart_cvr"
      ZERO_CHANGE_DB:  "postgresql://casefiles:a8f5f167f44f4964e6c998dee827110c@dev_postgres:5432/zstart_cdb"
      ZERO_REPLICA_FILE: /tmp/zstart_replica.db
      ZERO_SCHEMA_FILE:  ./zero-schema.json
    ports:
      - published: 4848
        target: 4848
    volumes:
      - type: volume
        source: zero_replica
        target: /tmp
      - type: bind
        source: ../../zero-schema.json
        target: /opt/app/zero-schema.json
    networks:
      - vps

  clerk_webhook:
    image: ghcr.io/baranuel/clerk-casefiles:latest
    env_file:
      - ./.env
    ports:
      - published: 1111
        target: 1111
    networks:
      - vps
