version: "3.8"

networks:
  vps_network:
    external: true

volumes:
  zstart_pgdata:
    driver: local
  zero_replica:
    driver: local

services:
  frontend:
    image: ghcr.io/baranuel/casefiles:${GIT_COMMIT_HASH:-latest}
    env_file:
      - ./.env
    networks:
      - vps_network

  postgres:
    image: postgres:16.2-alpine
    user: postgres
    healthcheck:
      test: ["CMD‑SHELL", "pg_isready -U ${POSTGRES_USER} --dbname=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - published: 5430
        target: 5432
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=5
      -c hot_standby=on
      -c hot_standby_feedback=on
    volumes:
      # named volume for PG data
      - type: volume
        source: zstart_pgdata
        target: /var/lib/postgresql/data

      # bind‑mount your init scripts directory;
      # make sure this exact path exists on every Swarm node
      - type: bind
        source: /home/ubuntu/case-files-react/docker       # ← adjust to your real absolute path
        target: /docker-entrypoint-initdb.d
    networks:
      - vps_network
    deploy:
      # example: ensure this service only ever runs on the manager
      placement:
        constraints:
          - node.role == manager

  zero:
    image: rocicorp/zero:0.12.2025013100
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      ZERO_UPSTREAM_DB: ${ZERO_UPSTREAM_DB}
      ZERO_CVR_DB:     ${ZERO_CVR_DB}
      ZERO_CHANGE_DB:  ${ZERO_CHANGE_DB}
      ZERO_REPLICA_FILE: /tmp/zstart_replica.db
      ZERO_SCHEMA_FILE:  ./zero-schema.json
    ports:
      - published: 4848
        target: 4848
    volumes:
      # bind your schema JSON
      - type: bind
        source: /home/ubuntu/case-files-react/zero-schema.json  
        target: /opt/app/zero-schema.json

      # named volume for Zero's replica DB
      - type: volume
        source: zero_replica
        target: /tmp/zstart_replica.db
    networks:
      - vps_network
    deploy:
      replicas: 1
