services:
  zstart_postgres:
    image: postgres:16.2-alpine
    shm_size: 1g
    user: postgres
    restart: always
    healthcheck:
      test: 'pg_isready -U user --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    command: |
      postgres 
      -c wal_level=logical
      -c max_wal_senders=10 
      -c max_replication_slots=5 
      -c hot_standby=on 
      -c hot_standby_feedback=on
    volumes:
      - zstart_pgdata:/var/lib/postgresql/data
      - ./:/docker-entrypoint-initdb.d

  zero:
    platform: linux/amd64
    depends_on:
      zstart_postgres:
        condition: service_healthy
    image: rocicorp/zero:0.12.2025013100
    volumes:
      - ../zero-schema.json:/opt/app/zero-schema.json
    env_file:
      - ../.env.production
    environment:
      - ZERO_UPSTREAM_DB=${ZERO_UPSTREAM_DB}
      - ZERO_CVR_DB=${ZERO_CVR_DB}
      - ZERO_CHANGE_DB=${ZERO_CHANGE_DB}
      - ZERO_AUTH_JWK=${ZERO_AUTH_JWK}
      - ZERO_REPLICA_FILE=/tmp/zstart_replica.db
      - ZERO_SCHEMA_FILE=./zero-schema.json
    ports:
      - 4848:4848

volumes:
  zstart_pgdata:
    driver: local
  zero_replica:
    driver: local